name: Build
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: rm -fr .paradicms
      - uses: paradicms/etl-action@v1-beta
        with:
          input_data: Passion
          input_format: markdown
          output_data: .paradicms/data/loaded
          output_format: ttl-rdf
        if: steps.extract_branch.outputs.branch == 'master'
      - run: cat .paradicms/data/loaded/Bildungsroman.ttl
