name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paradicms/action@v1-beta
        with:
          debug: 1
          base_url_path: /Passion
          configuration_file_path: ./configuration.ttl
          input_data: ./Passion
          input_format: markdown
          output_data: ./.github/pages/Passion
          output_format: exhibition
      - uses: paradicms/action@v1-beta
        with:
          debug: 1
          base_url_path: /Thinker-Doer
          configuration_file_path: ./configuration.ttl
          input_data: ./Thinker-Doer
          input_format: markdown
          output_data: ./.github/pages/Thinker-Doer
          output_format: exhibition
      - uses: peaceiris/actions-gh-pages@v3
        with:
          cname: bildungsroman.minorgordon.net
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.github/pages
