name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: paradicms/gui-action@v1-beta
        with:
          debug: 1
          base_url_path: /Passion
          configuration_json_file_path: ./Passion/configuration.json
          input_data: ./Passion
          input_format: markdown
          output_data: ./github/pages/Passion
          output_format: bootstrap-exhibition
      - uses: peaceiris/actions-gh-pages@v3
        with:
          cname: bildungsroman.minorgordon.net
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github/pages
